// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwl5fN6vW0mejZCZLKLLzmUC4_cBn46r8',
    appId: '1:553136522970:web:ddf39a5395708c471cc7e3',
    messagingSenderId: '553136522970',
    projectId: 'parvaah-fcf5e',
    authDomain: 'parvaah-fcf5e.firebaseapp.com',
    databaseURL:
        'https://parvaah-fcf5e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'parvaah-fcf5e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Ut2mAe16H2OR0HZ99A3PtsiCTfivgy8',
    appId: '1:553136522970:android:400f6808af1f8fc51cc7e3',
    messagingSenderId: '553136522970',
    projectId: 'parvaah-fcf5e',
    databaseURL:
        'https://parvaah-fcf5e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'parvaah-fcf5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk-ijogAUEZeW1DS9HmtMTOAUsUbWbDUo',
    appId: '1:553136522970:ios:64df139d8e96cbfa1cc7e3',
    messagingSenderId: '553136522970',
    projectId: 'parvaah-fcf5e',
    databaseURL:
        'https://parvaah-fcf5e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'parvaah-fcf5e.appspot.com',
    androidClientId:
        '553136522970-7vmbpmjmgud3a7cpbkd4bh96t3dqv8tg.apps.googleusercontent.com',
    iosClientId:
        '553136522970-carilt00tqisb1d1nrip3216lf898efb.apps.googleusercontent.com',
    iosBundleId: 'com.example.parvaahHelpingHand',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk-ijogAUEZeW1DS9HmtMTOAUsUbWbDUo',
    appId: '1:553136522970:ios:319bd86acf110eec1cc7e3',
    messagingSenderId: '553136522970',
    projectId: 'parvaah-fcf5e',
    databaseURL:
        'https://parvaah-fcf5e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'parvaah-fcf5e.appspot.com',
    androidClientId:
        '553136522970-7vmbpmjmgud3a7cpbkd4bh96t3dqv8tg.apps.googleusercontent.com',
    iosClientId:
        '553136522970-l7nrjejknerg60ave8j883kjke11surv.apps.googleusercontent.com',
    iosBundleId: 'com.example.parvaahHelpingHand.RunnerTests',
  );
}
